/*
 * PEX4GuiBuilderView.java
 */

package pex4guibuilder;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class PEX4GuiBuilderView extends FrameView {

    public PEX4GuiBuilderView(SingleFrameApplication app) {
        super(app);

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SettingsFrame = new javax.swing.JPanel();
        GameModeFrame = new javax.swing.JPanel();
        lblGameMode = new javax.swing.JLabel();
        rbtnLocal = new javax.swing.JRadioButton();
        rbtnRemote = new javax.swing.JRadioButton();
        rbtnComp = new javax.swing.JRadioButton();
        BoardSizeFrame = new javax.swing.JPanel();
        lblBoardSize = new javax.swing.JLabel();
        txtColumns = new javax.swing.JTextField();
        txtRows = new javax.swing.JTextField();
        lblColumns = new javax.swing.JLabel();
        lblRows = new javax.swing.JLabel();
        FirstPlayerFrame = new javax.swing.JPanel();
        lblFirstPlayer = new javax.swing.JLabel();
        rbtnRed = new javax.swing.JRadioButton();
        rbtnYellow = new javax.swing.JRadioButton();
        btnStartGame = new javax.swing.JButton();
        btngrpGameMode = new javax.swing.ButtonGroup();
        btngrpFirstPlayer = new javax.swing.ButtonGroup();
        GameFrame = new javax.swing.JPanel();
        gamePanel = new javax.swing.JPanel();

        SettingsFrame.setMinimumSize(new java.awt.Dimension(400, 400));
        SettingsFrame.setName("SettingsFrame"); // NOI18N
        SettingsFrame.setPreferredSize(new java.awt.Dimension(400, 400));

        GameModeFrame.setName("GameModeFrame"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pex4guibuilder.PEX4GuiBuilderApp.class).getContext().getResourceMap(PEX4GuiBuilderView.class);
        lblGameMode.setText(resourceMap.getString("lblGameMode.text")); // NOI18N
        lblGameMode.setName("lblGameMode"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pex4guibuilder.PEX4GuiBuilderApp.class).getContext().getActionMap(PEX4GuiBuilderView.class, this);
        rbtnLocal.setAction(actionMap.get("showValidFields")); // NOI18N
        btngrpGameMode.add(rbtnLocal);
        rbtnLocal.setSelected(true);
        rbtnLocal.setText(resourceMap.getString("rbtnLocal.text")); // NOI18N
        rbtnLocal.setActionCommand(resourceMap.getString("rbtnLocal.actionCommand")); // NOI18N
        rbtnLocal.setName("rbtnLocal"); // NOI18N

        rbtnRemote.setAction(actionMap.get("hideInvalidFields")); // NOI18N
        btngrpGameMode.add(rbtnRemote);
        rbtnRemote.setText(resourceMap.getString("rbtnRemote.text")); // NOI18N
        rbtnRemote.setName("rbtnRemote"); // NOI18N

        rbtnComp.setAction(actionMap.get("showValidFields")); // NOI18N
        btngrpGameMode.add(rbtnComp);
        rbtnComp.setText(resourceMap.getString("rbtnComp.text")); // NOI18N
        rbtnComp.setName("rbtnComp"); // NOI18N

        javax.swing.GroupLayout GameModeFrameLayout = new javax.swing.GroupLayout(GameModeFrame);
        GameModeFrame.setLayout(GameModeFrameLayout);
        GameModeFrameLayout.setHorizontalGroup(
            GameModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModeFrameLayout.createSequentialGroup()
                .addGroup(GameModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGameMode)
                    .addGroup(GameModeFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbtnComp)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(GameModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GameModeFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(GameModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbtnLocal)
                        .addComponent(rbtnRemote))
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        GameModeFrameLayout.setVerticalGroup(
            GameModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameModeFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGameMode)
                .addGap(64, 64, 64)
                .addComponent(rbtnComp))
            .addGroup(GameModeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GameModeFrameLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(rbtnLocal)
                    .addGap(6, 6, 6)
                    .addComponent(rbtnRemote)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        BoardSizeFrame.setName("BoardSizeFrame"); // NOI18N

        lblBoardSize.setText(resourceMap.getString("lblBoardSize.text")); // NOI18N
        lblBoardSize.setName("lblBoardSize"); // NOI18N

        txtColumns.setText(resourceMap.getString("txtColumns.text")); // NOI18N
        txtColumns.setName("txtColumns"); // NOI18N
        txtColumns.setPreferredSize(new java.awt.Dimension(20, 20));

        txtRows.setText(resourceMap.getString("txtRows.text")); // NOI18N
        txtRows.setName("txtRows"); // NOI18N
        txtRows.setPreferredSize(new java.awt.Dimension(20, 20));

        lblColumns.setText(resourceMap.getString("lblColumns.text")); // NOI18N
        lblColumns.setName("lblColumns"); // NOI18N

        lblRows.setText(resourceMap.getString("lblRows.text")); // NOI18N
        lblRows.setName("lblRows"); // NOI18N

        javax.swing.GroupLayout BoardSizeFrameLayout = new javax.swing.GroupLayout(BoardSizeFrame);
        BoardSizeFrame.setLayout(BoardSizeFrameLayout);
        BoardSizeFrameLayout.setHorizontalGroup(
            BoardSizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardSizeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoardSizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoardSize)
                    .addGroup(BoardSizeFrameLayout.createSequentialGroup()
                        .addGroup(BoardSizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColumns)
                            .addComponent(lblRows))
                        .addGap(18, 18, 18)
                        .addGroup(BoardSizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BoardSizeFrameLayout.setVerticalGroup(
            BoardSizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardSizeFrameLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblBoardSize)
                .addGap(18, 18, 18)
                .addGroup(BoardSizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColumns)
                    .addComponent(txtColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoardSizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRows)
                    .addComponent(txtRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FirstPlayerFrame.setName("FirstPlayerFrame"); // NOI18N

        lblFirstPlayer.setText(resourceMap.getString("lblFirstPlayer.text")); // NOI18N
        lblFirstPlayer.setName("lblFirstPlayer"); // NOI18N

        btngrpFirstPlayer.add(rbtnRed);
        rbtnRed.setSelected(true);
        rbtnRed.setText(resourceMap.getString("rbtnRed.text")); // NOI18N
        rbtnRed.setName("rbtnRed"); // NOI18N

        btngrpFirstPlayer.add(rbtnYellow);
        rbtnYellow.setText(resourceMap.getString("rbtnYellow.text")); // NOI18N
        rbtnYellow.setName("rbtnYellow"); // NOI18N

        javax.swing.GroupLayout FirstPlayerFrameLayout = new javax.swing.GroupLayout(FirstPlayerFrame);
        FirstPlayerFrame.setLayout(FirstPlayerFrameLayout);
        FirstPlayerFrameLayout.setHorizontalGroup(
            FirstPlayerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstPlayerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FirstPlayerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstPlayer)
                    .addComponent(rbtnRed)
                    .addComponent(rbtnYellow))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        FirstPlayerFrameLayout.setVerticalGroup(
            FirstPlayerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstPlayerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFirstPlayer)
                .addGap(17, 17, 17)
                .addComponent(rbtnRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnYellow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnStartGame.setAction(actionMap.get("startGame")); // NOI18N
        btnStartGame.setText(resourceMap.getString("btnStartGame.text")); // NOI18N
        btnStartGame.setName("btnStartGame"); // NOI18N
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });
        btnStartGame.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnStartGamePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout SettingsFrameLayout = new javax.swing.GroupLayout(SettingsFrame);
        SettingsFrame.setLayout(SettingsFrameLayout);
        SettingsFrameLayout.setHorizontalGroup(
            SettingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsFrameLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(SettingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnStartGame)
                        .addComponent(FirstPlayerFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoardSizeFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GameModeFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SettingsFrameLayout.setVerticalGroup(
            SettingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsFrameLayout.createSequentialGroup()
                .addComponent(GameModeFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoardSizeFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(FirstPlayerFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartGame)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        GameFrame.setName("GameFrame"); // NOI18N
        GameFrame.setPreferredSize(new java.awt.Dimension(600, 600));

        gamePanel.setName("gamePanel"); // NOI18N

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GameFrameLayout = new javax.swing.GroupLayout(GameFrame);
        GameFrame.setLayout(GameFrameLayout);
        GameFrameLayout.setHorizontalGroup(
            GameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameFrameLayout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(114, 114, 114)
                .addComponent(gameCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
=======
                .addGap(70, 70, 70)
                .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
>>>>>>> 37fc855810b14540bc02c11d30c380306f8abc72
        );
        GameFrameLayout.setVerticalGroup(
            GameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameFrameLayout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(40, 40, 40)
                .addComponent(gameCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
=======
                .addGap(82, 82, 82)
                .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
>>>>>>> 37fc855810b14540bc02c11d30c380306f8abc72
        );

        setComponent(SettingsFrame);
    }// </editor-fold>//GEN-END:initComponents

  private void btnStartGamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnStartGamePropertyChange

  }//GEN-LAST:event_btnStartGamePropertyChange

  private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed

  }//GEN-LAST:event_btnStartGameActionPerformed

  public void playGame() {
<<<<<<< HEAD
    //gameCanvas.setBounds(10, 10, 100, 100);
    //gameCanvas.setBackground(Color.black);
    gameCanvas.setupGameCanvas();
    
    //image = new BufferedImage(gameCanvas.getWidth(), gameCanvas.getHeight(), BufferedImage.TYPE_INT_RGB);
    //gameCanvas.setImage(image);
    Graphics2D g = gameCanvas.getGraphics();
    g.setColor(Color.red);
    g.fillOval(100, 100, 50, 50);
    //gameCanvas.setImage(image);
    gameCanvas.paint(g);
    GameFrame.update(g);
    
    gameCanvas.saveGraphics("test.jpg");
=======
    //gameCanvas.setBounds(50, 50, 250, 250);
    //gameCanvas.setupGameCanvas();
    //gamePanel.setBackground(Color.white);
    
    //image = new BufferedImage(gameCanvas.getWidth(), gameCanvas.getHeight(), BufferedImage.TYPE_INT_RGB);
    //gameCanvas.setImage(image);
//    Graphics2D g = (Graphics2D) gamePanel.getGraphics();
//    g.setColor(Color.red);
//    g.fillOval(50, 50, 50, 50);
    //gamePanel.paint(g);
    //gameCanvas.setImage(image);
    //gameCanvas.paint(g);
    //gameCanvas.saveGraphics("test.jpg");
    
    DrawingPanel panel = new DrawingPanel(600,600);
    panel.setBackground(Color.blue);
    Graphics2D g = (Graphics2D) panel.getGraphics();
    drawGrid(g);
    Scanner input = new Scanner(System.in);
    panel.copyGraphicsToScreen();
    while (!game.redWon() && !game.yellowWon() && !game.isTie()) {
      System.out.println("Turn: " + game.whoseTurn());
      if (game.whoseTurn().equals("Red") || game.getGameMode() == 1) {
        //game.nextMove(getMove(input));
        game.nextMove(getMove(panel));
      } else {
        game.nextMove();
      }
      drawMove(g);
      System.out.println(game.toString());
      panel.copyGraphicsToScreen();
    }

    if (game.redWon()) {
      System.out.println("Red Won!");
    } else {
      if (game.yellowWon()) {
        System.out.println("Yellow Won!");
      } else {
        System.out.println("Tie game.");
      }
    }
    panel.copyGraphicsToScreen();
  }
  
  public int getMove(Scanner input) {
    int move = 0;
    while (move < 1 || move > 7) {
      System.out.print("Enter move (1-7): ");
      if (input.hasNextInt()) {
        move = input.nextInt();
      } else {
        input.next();  // discard bad input
        move = 0;
      }
    }
    return move;
  }
  
  public int getMove(DrawingPanel panel) {
    while (!panel.mouseClickHasOccurred(DrawingPanel.LEFT_BUTTON)) {
      System.out.println(panel.getMouseX());
      
    }
    return 1;
  }
  
  public void drawGrid(Graphics2D g) {
    Color oldColor = g.getColor();
    g.setColor(Color.white);
    for (int rows = 0, rowSpacer = (600/(game.getRows()))/2; rows < game.getRows(); rows++, rowSpacer += 600/(game.getColumns()+1)) {
      for (int columns = 0, colSpacer = (600/game.getColumns())/2; columns < game.getColumns(); columns++, colSpacer += 600/(game.getColumns()+1)) {
        g.fillOval(colSpacer, rowSpacer, 75,75);
      }
    }
    g.setColor(oldColor);
  }
  
  public void drawMove(Graphics2D g) {
    int[] lastMove = game.getLastMove();
    int xPos = lastMove[1] * (600/(game.getColumns()+1)) + (600/game.getColumns())/2;
    int yPos = lastMove[0] * (600/(game.getColumns()+1)) + (600/game.getRows())/2;
    Color oldColor = g.getColor();
    if (!game.whoseTurn().equals("Red")) {
      g.setColor(Color.red);
    }
    else {
      g.setColor(Color.yellow);
    }
    
    g.fillOval(xPos, yPos, 75, 75);
    g.setColor(oldColor);
>>>>>>> 37fc855810b14540bc02c11d30c380306f8abc72
  }
  
  @Action
  public void startGame() {
    int gameMode = 0;
    if (rbtnLocal.isSelected()) {
      gameMode = 1;
    }
    else if (rbtnRemote.isSelected()) {
      gameMode = 2;
    }
    else if (rbtnComp.isSelected()) {
      gameMode = 3;
    }
    int rows = Integer.parseInt(txtRows.getText());
    int columns = Integer.parseInt(txtColumns.getText());
    int firstPlayer = 0;
    if (rbtnRed.isSelected()) {
      firstPlayer = 1;
    }
    else if (rbtnYellow.isSelected()) {
      firstPlayer = 2;
    }
    game = new Connect4(rows,columns,gameMode,firstPlayer);
//    SettingsFrame.setVisible(false);
//    setComponent(GameFrame);
    playGame();
  }

  @Action
  public void hideInvalidFields() {
    lblFirstPlayer.setEnabled(false);
    rbtnRed.setEnabled(false);
    rbtnYellow.setEnabled(false);
  }

  @Action
  public void showValidFields() {
    lblFirstPlayer.setEnabled(true);
    rbtnRed.setEnabled(true);
    rbtnYellow.setEnabled(true);
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardSizeFrame;
    private javax.swing.JPanel FirstPlayerFrame;
    private javax.swing.JPanel GameFrame;
    private javax.swing.JPanel GameModeFrame;
    private javax.swing.JPanel SettingsFrame;
    private javax.swing.JButton btnStartGame;
    private javax.swing.ButtonGroup btngrpFirstPlayer;
    private javax.swing.ButtonGroup btngrpGameMode;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel lblBoardSize;
    private javax.swing.JLabel lblColumns;
    private javax.swing.JLabel lblFirstPlayer;
    private javax.swing.JLabel lblGameMode;
    private javax.swing.JLabel lblRows;
    private javax.swing.JRadioButton rbtnComp;
    private javax.swing.JRadioButton rbtnLocal;
    private javax.swing.JRadioButton rbtnRed;
    private javax.swing.JRadioButton rbtnRemote;
    private javax.swing.JRadioButton rbtnYellow;
    private javax.swing.JTextField txtColumns;
    private javax.swing.JTextField txtRows;
    // End of variables declaration//GEN-END:variables
    private Connect4 game = null;
    private BufferedImage image;
}
